name: Tests

on:
  push:
    branches: [ "react-ssr" ]

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install modules
        run: npm ci
      - name: Run Unit Tests
        run: npm run test
      - name: Unit Test Coverage
        run: npm run coverage:unit
    
    outputs:
      status: ${{ job.status }}

  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install modules
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:5173"